title: Thales
description: A Guide to Celestia Web Platforms
baseurl: "/"
url: ""

permalink: pretty
exclude: ["*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  rel_url: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Visit SEDS Celestia":
    - "sedscelestia.org"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 SEDS Celestia. Built by Plutoniumm."

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: "light"

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: none
  endings: all
  startings: []
  blanklines: false
  profile: false